import React from "react"
import type { Metadata, Viewport } from 'next'
import { Inter, Space_Grotesk } from 'next/font/google'
import { Toaster } from 'sonner'

import { Providers } from "./providers"
import './globals.css'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const spaceGrotesk = Space_Grotesk({ subsets: ['latin'], variable: '--font-space-grotesk' })

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
}

export const metadata: Metadata = {
  title: 'DND Purchase - Buy/Sell Steel and Cement in 2-steps',
  description: 'Best Pricing. Zero Calls.',
  keywords: [
    "dnd",
    "dnd purchase",
    "dnd marketplace",
    "dnd b2b platform",
    "dnd purchase login",
    "dnd purchase app",
    "b2b marketplace",
    "b2b marketplace India",
    "industrial marketplace",
    "business purchasing platform",
    "b2b e-commerce platform",
    "wholesale marketplace",
    "bulk buying marketplace",
    "procurement marketplace",
    "industrial buying platform",
    "b2b procurement",
    "digital marketplace",
    "online business marketplace",
    "company purchasing platform",
    "b2b sales platform",
    "buy steel",
    "buy steel online",
    "buy steel India",
    "buy steel online India",
    "steel purchase",
    "steel purchase online",
    "buy ms steel",
    "buy structural steel",
    "buy steel rod",
    "buy steel pipe",
    "buy steel coil",
    "buy steel sheet",
    "buy steel plate",
    "buy deformed steel bar",
    "buy tmt bar",
    "buy reinforcement steel",
    "buy iron steel",
    "buy carbon steel",
    "buy alloy steel",
    "buy stainless steel",
    "buy mild steel",
    "buy galvanized steel",
    "sell steel",
    "sell steel online",
    "steel supplier",
    "steel seller",
    "steel dealer",
    "steel wholesaler",
    "steel distributor",
    "steel manufacturer",
    "steel stockist",
    "steel vendor",
    "ms steel",
    "tmt steel",
    "structural steel",
    "steel rods",
    "steel bars",
    "steel coils",
    "steel sheets",
    "steel plates",
    "steel pipes",
    "steel tubes",
    "rebar",
    "deformed bar",
    "rolling mills",
    "buy cement",
    "buy cement online",
    "buy cement online India",
    "buy cement bulk",
    "buy opc cement",
    "buy ppc cement",
    "buy psc cement",
    "buy white cement",
    "buy portland cement",
    "buy rapid hardening cement",
    "buy cement online cheap",
    "buy construction cement",
    "buy building cement",
    "buy industrial cement",
    "cement purchase",
    "cement supplier",
    "cement dealer",
    "cement wholesaler",
    "cement distributor",
    "cement stockist",
    "cement manufacturer",
    "opc cement",
    "ppc cement",
    "psc cement",
    "white cement",
    "portland cement",
    "ordinary portland cement",
    "pozzolana cement",
    "slag cement",
    "fly ash cement",
    "ready mix cement",
    "bag cement",
    "bulk cement",
    "construction materials",
    "buy construction materials",
    "construction material supplier",
    "building materials",
    "buy building materials",
    "building material supplier",
    "buy building material online",
    "industrial construction materials",
    "buy metal",
    "buy metal online",
    "buy aluminum",
    "buy copper",
    "buy brass",
    "buy zinc",
    "buy lead",
    "buy nickel",
    "buy iron",
    "buy iron online",
    "buy iron rod",
    "buy iron pipe",
    "buy cast iron",
    "buy iron scrap",
    "buy sand",
    "buy sand online",
    "buy aggregates",
    "buy aggregates online",
    "buy stone aggregates",
    "buy roddum",
    "buy crush sand",
    "buy bricks",
    "buy bricks online",
    "buy red bricks",
    "buy fire bricks",
    "buy aac blocks",
    "buy concrete blocks",
    "buy hollow blocks",
    "industrial raw materials",
    "industrial materials",
    "buy raw materials",
    "bulk raw materials",
    "manufacturing raw materials",
    "industrial chemical raw materials",
    "buy coal",
    "buy coal online",
    "buy limestone",
    "buy dolomite",
    "buy bauxite",
    "buy manganese ore",
    "do not disturb purchase",
    "do not disturb marketplace",
    "dnd buying",
    "noise free purchasing",
    "spam free marketplace",
    "disturbance free buying",
    "unwanted call free purchase",
    "private buying platform",
    "discreet purchase",
    "confidential purchasing",
    "no spam marketplace",
    "no telemarketing marketplace",
    "verified buyer marketplace",
    "serious buyer platform",
    "business purchase",
    "corporate buying",
    "company purchase",
    "bulk order",
    "bulk purchase",
    "wholesale buying",
    "procurement",
    "tender purchase",
    "b2b transaction",
    "b2b deal",
    "business to business sale",
    "commercial purchase",
    "industrial sale",
    "become supplier",
    "sell products",
    "register as seller",
    "b2b seller",
    "verified seller",
    "supplier registration",
    "buyer inquiry",
    "post requirement",
    "request quotation",
    "get quote",
    "submit tender",
    "steel price",
    "cement price",
    "tmt price today",
    "steel rate",
    "cement rate",
    "price per ton",
    "current steel price",
    "current cement price",
    "buy steel Mumbai",
    "buy steel Delhi",
    "buy steel Bangalore",
    "buy steel Chennai",
    "buy steel Kolkata",
    "buy steel Hyderabad",
    "buy steel Pune",
    "buy steel Ahmedabad",
    "buy steel Gujarat",
    "buy steel Maharashtra",
    "buy steel Tamil Nadu",
    "buy steel Karnataka",
    "indiamart alternative",
    "tradeindia alternative",
    "mjunction alternative",
    "alibaba b2b india",
    "best steel supplier",
    "best cement brand",
    "cheapest steel online",
    "quality steel supplier",
    "reliable cement dealer",
    "trusted marketplace",
    "secure payment marketplace",
    "where to buy steel",
    "how to buy cement bulk",
    "online steel purchase site",
    "best marketplace for steel",
    "proven b2b platform",
    "automotive industry steel",
    "construction industry materials",
    "manufacturing sector steel",
    "infrastructure project materials"
  ]
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${inter.variable} ${spaceGrotesk.variable} font-sans antialiased min-h-screen min-h-dvh bg-background`}
      >
        <Providers>{children}</Providers>
        <Toaster position="top-right" richColors />
      </body>
    </html>


  )
}
